### ISSUE TITLE
Kolokvij

### ISSUE THREAD

**Issue by tsculac** [MiaOberan/PAF#6]
- 1. zadatak: **12/20** ne ispisuje se odmah kod stvaranja objekta u funkciji __init__()
- 2. zadatak: **5/20** nema metoda za promjenu brzine/visine
- 3. zadatak: **0/20** 
- 4. zadatak: **0/20** 
- 5. zadatak: **0/20**
Ukupno: **17/100**

**Comment by MiaOberan** [comment]
Lijep pozdrav Poštovani, usporedila sam rezultate sa kolegicama koje su imali isti komentar za prvi zadatak ali su one dobila 15 bodova. Jesam li jos nesto pogrijesila? Sljedece pitanje je za polaganje kolegija, zar niste rekli da je 45 bodova za polozit ga a ne 50 (prva prezentacija) ?

**Comment by tsculac** [comment]
Kolege koji su imali zaseban program za zadatak 1 u kojem pozivaju objekt su dobili još 3 boda u prvom zadatku. U pravu ste za polaganje kolegija, napravio sam pogrešku u prethodnom mailu i točan broj bodova je 45. Hvala na ispravci :)

**Comment by MiaOberan** [comment]
Hvala Vama, sad mi je jasno! Ugodan dan :)
